# Generated by Django 4.0.4 on 2022-05-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('grade', models.CharField(choices=[('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=25)),
                ('subject', models.CharField(choices=[('English', 'English'), ('Mathematics', 'Mathematics')], max_length=25)),
            ],
        ),
    ]
